services:
  lampac:
    build: .
    container_name: beam-balancers
    ports:
      - "9118:9118"
    volumes:
      - ./init.conf:/app/init.conf:ro
      - ./database:/app/database
    restart: unless-stopped
    shm_size: 1024mb
    environment:
      - TZ=Europe/Kyiv
